# This workflow will build the docker image
# and push it to a private repository

name: Build + Push Image To Docker Hub

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: jliu1272/gh-actions-demo-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
